/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Profile;


/**
 *
 * @author Harshit
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Profile profile;
    
    public boolean isSubmit = true;    
    public boolean isSubmit_Name = false;
    public boolean isSubmit_Address = false;
    public boolean isSubmit_DOB = false;
    public boolean isSubmit_telephoneNumber = false;
    public boolean isSubmit_FaxNumber = false;
    public boolean isSubmit_EmailAddress = false;
    public boolean isSubmit_SSN = false;
    public boolean isSubmit_MedicalRecordNumber = false;
    public boolean isSubmit_BankAccountNumber = false;
    public boolean isSubmit_LicenseNumber = false;
    public boolean isSubmit_LinkedinURL = false;
    public boolean isSubmit_IPAddress = false;
    public boolean isSubmit_Photo = false;
    
    
    
    
    
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1Title = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblVehicleIdentifierNumber = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtVehicleIdentifierNumber = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtDOB = new com.toedter.calendar.JDateChooser();
        btnAttach = new javax.swing.JButton();
        txtFilePath = new javax.swing.JTextField();
        txtViewPhoto = new javax.swing.JLabel();

        lb1Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb1Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1Title.setText("CREATE PROFILE");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Name:");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Address:");

        lblDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date of Birth");

        lblTelephoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelephoneNumber.setText("Telephone Number:");

        lblFaxNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaxNumber.setText("Fax Number: ");

        lblEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmailAddress.setText("Email Address:");

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number:");

        lblMedicalRecordNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number:");

        lblBankAccountNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankAccountNumber.setText("Bank Account Number:");

        lblLicenseNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLicenseNumber.setText("License Number:");

        lblVehicleIdentifierNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVehicleIdentifierNumber.setText("Vehicle Identifier Number: ");

        lblDeviceIdentifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeviceIdentifier.setText("Device Identifier: ");

        lblLinkedin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinkedin.setText("Linkedin URL: ");

        lblIPAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIPAddress.setText("IP Address:");

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhoto.setText("Upload Photo:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });

        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });
        txtTelephoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneNumberKeyReleased(evt);
            }
        });

        txtFaxNumber.setToolTipText("Optional");
        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });
        txtFaxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumberKeyReleased(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        txtMedicalRecordNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumberKeyReleased(evt);
            }
        });

        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });
        txtBankAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccountNumberKeyReleased(evt);
            }
        });

        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });
        txtLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicenseNumberKeyReleased(evt);
            }
        });

        txtVehicleIdentifierNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtVehicleIdentifierNumber.setText("Optional");
        txtVehicleIdentifierNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierNumberFocusLost(evt);
            }
        });
        txtVehicleIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentifierNumberActionPerformed(evt);
            }
        });

        txtDeviceIdentifier.setForeground(new java.awt.Color(153, 153, 153));
        txtDeviceIdentifier.setText("Optional");
        txtDeviceIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceIdentifierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIdentifierFocusLost(evt);
            }
        });
        txtDeviceIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });
        txtLinkedin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedinKeyReleased(evt);
            }
        });

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });
        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDOB.setForeground(new java.awt.Color(255, 2, 6));
        txtDOB.setMinimumSize(new java.awt.Dimension(28, 30));

        btnAttach.setText("Browse...");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb1Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblAddress))
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateOfBirth)
                            .addComponent(lblTelephoneNumber)
                            .addComponent(lblFaxNumber)
                            .addComponent(lblEmailAddress)
                            .addComponent(lblSSN)
                            .addComponent(lblMedicalRecordNumber)
                            .addComponent(lblBankAccountNumber)
                            .addComponent(lblLicenseNumber)
                            .addComponent(lblVehicleIdentifierNumber)
                            .addComponent(lblDeviceIdentifier)
                            .addComponent(lblLinkedin)
                            .addComponent(lblIPAddress)
                            .addComponent(lblPhoto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtFaxNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnSave)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtViewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtViewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblTelephoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFaxNumber)
                                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmailAddress)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSSN)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMedicalRecordNumber)
                                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBankAccountNumber)
                                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicenseNumber)
                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIdentifierNumber)
                    .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddress)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtVehicleIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierNumberActionPerformed

    private void txtDeviceIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:    

        if(this.isSubmit_Name == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid name.");
        }
        else if(this.isSubmit_Address == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid address.");
        }
        else if(txtDOB.getDate() == null){
            JOptionPane.showMessageDialog(this, "Please enter a valid date of birth.");
        }        
        else if(this.isSubmit_telephoneNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid telephone number.");
        }
        else if(this.isSubmit_FaxNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid fax number.");
        }
        else if(this.isSubmit_EmailAddress == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
        }
        else if(this.isSubmit_SSN == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid social security number.");
        }
        else if(this.isSubmit_MedicalRecordNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid medical record number.");
        }
        else if(this.isSubmit_BankAccountNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid bank account number.");
        }
        else if(this.isSubmit_LinkedinURL == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid linkedin URL.");
        }
        else if(this.isSubmit_IPAddress == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid IP Address.");
        }
        else if(this.isSubmit_Photo == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid photo.");
        }
        else{   
            profile.setName(txtName.getText());
            profile.setAddress(txtAddress.getText());
//            Date date_today = new Date();
//            if (txtDOB.getDate() == null){
//                profile.setDate_of_birth(date_today);
//            }
//            else{                
            profile.setDate_of_birth(txtDOB.getDate());
//            }
            profile.setTelephone_number(txtTelephoneNumber.getText());
            profile.setFax_number(txtFaxNumber.getText());
            profile.setEmail_address(txtEmailAddress.getText());
            profile.setSsn(txtSSN.getText());
            profile.setMedical_record_number(txtMedicalRecordNumber.getText());
            profile.setBank_account_number(txtBankAccountNumber.getText());
            profile.setLicense_number(txtLicenseNumber.getText());
            
            if(txtVehicleIdentifierNumber.getText().equals("Optional")){
                profile.setVehicle_identifier_number("");
            }
            else{
                profile.setVehicle_identifier_number(txtVehicleIdentifierNumber.getText());
            }
            
            if(txtDeviceIdentifier.getText().equals("Optional")){
                profile.setDevice_identifier("");
            }
            else{
                profile.setDevice_identifier(txtDeviceIdentifier.getText());
            }
            
            profile.setLinkedin(txtLinkedin.getText());
            profile.setIp_address(txtIPAddress.getText());
            profile.setPhoto(txtFilePath.getText());
            
            JOptionPane.showMessageDialog(this, "Profile Saved Successfully!");
        }        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTelephoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNumberKeyReleased
        // TODO add your handling code here:
        String telephoneNumber = txtTelephoneNumber.getText();
        if(telephoneNumber.matches("^[0-9]*$") && telephoneNumber.length() == 10)
        {
            txtTelephoneNumber.setBackground(Color.green);
            this.isSubmit_telephoneNumber = true;
        }
        else{
            txtTelephoneNumber.setBackground(Color.red);
            this.isSubmit_telephoneNumber = false;
        }
    }//GEN-LAST:event_txtTelephoneNumberKeyReleased

    private void txtFaxNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumberKeyReleased
        // TODO add your handling code here:
        String faxNumber = txtFaxNumber.getText();
        if(faxNumber.matches("^[0-9]*$") && faxNumber.length() == 9)
        {
            txtFaxNumber.setBackground(Color.green);
            this.isSubmit_FaxNumber = true;
        }
        else{
            txtFaxNumber.setBackground(Color.red);
            this.isSubmit_FaxNumber = false;
        }
    }//GEN-LAST:event_txtFaxNumberKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        String ssnNumber = txtSSN.getText();
        if(ssnNumber.matches("^[0-9]*$") && ssnNumber.length() == 9)
        {
            txtSSN.setBackground(Color.green);
            this.isSubmit_SSN = true;
        }
        else
            txtSSN.setBackground(Color.red);
            this.isSubmit_SSN = false;
        
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtMedicalRecordNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberKeyReleased
        // TODO add your handling code here:
        String medicalRecordNumber = txtMedicalRecordNumber.getText();
        if(medicalRecordNumber.matches("^[0-9]*$"))
        {
            txtMedicalRecordNumber.setBackground(Color.green);
            this.isSubmit_MedicalRecordNumber = true;
        }
        else
            txtMedicalRecordNumber.setBackground(Color.red);
            this.isSubmit_MedicalRecordNumber = false;
    }//GEN-LAST:event_txtMedicalRecordNumberKeyReleased

    private void txtBankAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountNumberKeyReleased
        // TODO add your handling code here:
        String bankAccountNumber = txtBankAccountNumber.getText();
        if(bankAccountNumber.matches("^[0-9]*$"))
        {
            txtBankAccountNumber.setBackground(Color.green);
            this.isSubmit_BankAccountNumber = true;
        }
        else
            txtBankAccountNumber.setBackground(Color.red);
            this.isSubmit_BankAccountNumber = false;
    }//GEN-LAST:event_txtBankAccountNumberKeyReleased

    private void txtLicenseNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNumberKeyReleased
        // TODO add your handling code here:
        String LicenseNumber = txtLicenseNumber.getText();
        if(LicenseNumber.matches("^[0-9]*$") && LicenseNumber.length() == 9)
        {
            txtLicenseNumber.setBackground(Color.green);
            this.isSubmit_LicenseNumber = true;
        }
        else
            txtLicenseNumber.setBackground(Color.red);
            this.isSubmit_LicenseNumber = false;
        
    }//GEN-LAST:event_txtLicenseNumberKeyReleased

    private void txtIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtIPAddressKeyReleased

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        //Attaching Filter to JFileChooser object
        chooser.addChoosableFileFilter(imageFilter);
        chooser.setAcceptAllFileFilterUsed(false);

        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txtFilePath.setText(filename);
        
        Image im = Toolkit.getDefaultToolkit().createImage(filename);
        im = im.getScaledInstance(txtViewPhoto.getWidth(), txtViewPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ii = new ImageIcon(im);
        txtViewPhoto.setIcon(ii);
        this.isSubmit_Photo = true;
        
        
        
        
    }//GEN-LAST:event_btnAttachActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String Name = txtName.getText();
        txtName.setBackground(Color.red);
        if(Name.isEmpty())
        {
            txtName.setBackground(Color.red);
            this.isSubmit_Name = false;
        }
        else{
            txtName.setBackground(Color.green);
            this.isSubmit_Name = true;
        }
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtVehicleIdentifierNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberFocusGained
        // TODO add your handling code here:
        if(txtVehicleIdentifierNumber.getText().equals("Optional")){
            txtVehicleIdentifierNumber.setText("");
            txtVehicleIdentifierNumber.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_txtVehicleIdentifierNumberFocusGained

    private void txtDeviceIdentifierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierFocusGained
        // TODO add your handling code here:
        if(txtDeviceIdentifier.getText().equals("Optional")){
            txtDeviceIdentifier.setText("");
            txtDeviceIdentifier.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtDeviceIdentifierFocusGained

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        // TODO add your handling code here:
        String Address = txtAddress.getText();
        txtAddress.setBackground(Color.red);
        if(Address.isEmpty())
        {
            txtAddress.setBackground(Color.red);
            this.isSubmit_Address = false;
        }
        else{
            txtAddress.setBackground(Color.green);
            this.isSubmit_Address = true;
        }
        
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtVehicleIdentifierNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberFocusLost
        // TODO add your handling code here:
        if(txtVehicleIdentifierNumber.getText().equals("")){
            txtVehicleIdentifierNumber.setText("Optional");
            txtVehicleIdentifierNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtVehicleIdentifierNumberFocusLost

    private void txtDeviceIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierFocusLost
        // TODO add your handling code here:
        if(txtDeviceIdentifier.getText().equals("")){
            txtDeviceIdentifier.setText("Optional");
            txtDeviceIdentifier.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtDeviceIdentifierFocusLost

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // TODO add your handling code here:
        String Email = txtEmailAddress.getText();
        
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        if(pattern.matcher(Email).matches()){
            txtEmailAddress.setBackground(Color.green);
            this.isSubmit_EmailAddress = true;
        }
        else{
            txtEmailAddress.setBackground(Color.red);
            this.isSubmit_EmailAddress = false;        
        }
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtLinkedinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedinKeyReleased
        // TODO add your handling code here:
        String LinkedinURL = txtLinkedin.getText();
        
        try {
            new URL(LinkedinURL).toURI();
            txtLinkedin.setBackground(Color.green);
            this.isSubmit_LinkedinURL = true;
        } catch (MalformedURLException | URISyntaxException ex) {
            txtLinkedin.setBackground(Color.red);
            this.isSubmit_LinkedinURL = false;  
        }
    }//GEN-LAST:event_txtLinkedinKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lb1Title;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblVehicleIdentifierNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankAccountNumber;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtVehicleIdentifierNumber;
    private javax.swing.JLabel txtViewPhoto;
    // End of variables declaration//GEN-END:variables
}
