/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Profile;


/**
 *
 * @author Harshit
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Profile profile;
    
    /**
     * Defines all the variables used for validation.
     */
    public boolean isSubmit_Name = false;
    public boolean isSubmit_Address = false;
    public boolean isSubmit_DOB = false;
    public boolean isSubmit_telephoneNumber = false;
    public boolean isSubmit_FaxNumber = false;
    public boolean isSubmit_EmailAddress = false;
    public boolean isSubmit_SSN = false;
    public boolean isSubmit_MedicalRecordNumber = false;
    public boolean isSubmit_BankAccountNumber = false;
    public boolean isSubmit_LicenseNumber = false;
    public boolean isSubmit_LinkedinURL = false;
    public boolean isSubmit_VehicleIdentifierNumber = false;
    public boolean isSubmit_IPAddress = false;
    public boolean isSubmit_Photo = false;
    public boolean isSubmit_Fingerprint = false;
    
    
    
    
    
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1Title = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblVehicleIdentifierNumber = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtVehicleIdentifierNumber = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtDOB = new com.toedter.calendar.JDateChooser();
        btnAttach = new javax.swing.JButton();
        txtFilePath = new javax.swing.JTextField();
        txtViewPhoto = new javax.swing.JLabel();
        lblFingerprint = new javax.swing.JLabel();
        btnAttachFingerprint = new javax.swing.JButton();
        txtFilePathFingerprint = new javax.swing.JTextField();
        txtViewFingerprint = new javax.swing.JLabel();

        lb1Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb1Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1Title.setText("CREATE PROFILE");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Full Name");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Address");

        lblDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date of Birth");

        lblTelephoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelephoneNumber.setText("Telephone Number");

        lblFaxNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaxNumber.setText("Fax Number");

        lblEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmailAddress.setText("Email Address");

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number");

        lblMedicalRecordNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number");

        lblBankAccountNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankAccountNumber.setText("Bank Account Number");

        lblLicenseNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLicenseNumber.setText("License Number");

        lblVehicleIdentifierNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVehicleIdentifierNumber.setText("Vehicle Identifier Number ");

        lblDeviceIdentifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeviceIdentifier.setText("Device Identifier ");

        lblLinkedin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinkedin.setText("Linkedin URL");

        lblIPAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIPAddress.setText("IP Address");

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhoto.setText("Upload Photo");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });

        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });
        txtTelephoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneNumberKeyReleased(evt);
            }
        });

        txtFaxNumber.setToolTipText("");
        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });
        txtFaxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumberKeyReleased(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        txtMedicalRecordNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumberKeyReleased(evt);
            }
        });

        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });
        txtBankAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccountNumberKeyReleased(evt);
            }
        });

        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });
        txtLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicenseNumberKeyReleased(evt);
            }
        });

        txtVehicleIdentifierNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtVehicleIdentifierNumber.setText("Optional");
        txtVehicleIdentifierNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierNumberFocusLost(evt);
            }
        });
        txtVehicleIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentifierNumberActionPerformed(evt);
            }
        });
        txtVehicleIdentifierNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleIdentifierNumberKeyReleased(evt);
            }
        });

        txtDeviceIdentifier.setForeground(new java.awt.Color(153, 153, 153));
        txtDeviceIdentifier.setText("Optional");
        txtDeviceIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceIdentifierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIdentifierFocusLost(evt);
            }
        });
        txtDeviceIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });
        txtLinkedin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedinKeyReleased(evt);
            }
        });

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });
        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDOB.setForeground(new java.awt.Color(255, 2, 6));
        txtDOB.setMinimumSize(new java.awt.Dimension(28, 30));

        btnAttach.setText("Browse...");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        txtViewPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtViewPhoto.setText("Your uploaded photo will display here.");

        lblFingerprint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFingerprint.setText("Upload Fingerprint");

        btnAttachFingerprint.setText("Browse...");
        btnAttachFingerprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachFingerprintActionPerformed(evt);
            }
        });

        txtViewFingerprint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtViewFingerprint.setText("Your uploaded fingerprint will display here.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb1Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblTelephoneNumber)
                    .addComponent(lblFaxNumber)
                    .addComponent(lblEmailAddress)
                    .addComponent(lblSSN)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(lblLicenseNumber)
                    .addComponent(lblVehicleIdentifierNumber)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(lblLinkedin)
                    .addComponent(lblIPAddress)
                    .addComponent(lblPhoto)
                    .addComponent(lblName)
                    .addComponent(lblAddress)
                    .addComponent(lblFingerprint))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtFaxNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAttachFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFilePathFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtViewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblTelephoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFaxNumber)
                                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmailAddress)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSSN)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMedicalRecordNumber)
                                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBankAccountNumber)
                                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicenseNumber)
                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicleIdentifierNumber)
                            .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeviceIdentifier)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedin)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIPAddress)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFingerprint)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAttachFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFilePathFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtViewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtViewFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtVehicleIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierNumberActionPerformed

    private void txtDeviceIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:    
            /**
            * Code to save the profile and do all the validations.
            */
        
        if(this.isSubmit_Name == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid name.");
        }
        else if(this.isSubmit_Address == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid address.");
        }
        else if(txtDOB.getDate() == null){
            JOptionPane.showMessageDialog(this, "Please enter a valid date of birth.");
        }        
        else if(this.isSubmit_telephoneNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid telephone number.");
        }
        else if(this.isSubmit_FaxNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid fax number.");
        }
        else if(this.isSubmit_EmailAddress == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
        }
        else if(this.isSubmit_SSN == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid social security number.");
        }
        else if(this.isSubmit_MedicalRecordNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid medical record number.");
        }
        else if(this.isSubmit_BankAccountNumber == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid bank account number.");
        }
        else if(this.isSubmit_LinkedinURL == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid linkedin URL.");
        }
        else if(this.isSubmit_IPAddress == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid IP Address.");
        }
        else if(this.isSubmit_Photo == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid photo.");
        }
        else if(this.isSubmit_Fingerprint == false ){
            JOptionPane.showMessageDialog(this, "Please enter a valid fingerprint.");
        }
        else{   
            
                /**
                * Sets all the variable values to the profile package
                */
            profile.setName(txtName.getText());
            profile.setAddress(txtAddress.getText());           
            profile.setDate_of_birth(txtDOB.getDate());
            profile.setTelephone_number(Long.parseLong(txtTelephoneNumber.getText()));
            profile.setFax_number(Long.parseLong(txtFaxNumber.getText()));
            profile.setEmail_address(txtEmailAddress.getText());
            profile.setSsn(Long.parseLong(txtSSN.getText()));
            profile.setMedical_record_number(Long.parseLong(txtMedicalRecordNumber.getText()));
            profile.setBank_account_number(Long.parseLong(txtBankAccountNumber.getText()));
            profile.setLicense_number(Long.parseLong(txtLicenseNumber.getText()));
            
            // Placeholder for Vehicle Identifier number.
            if(txtVehicleIdentifierNumber.getText().equals("Optional")){
                profile.setVehicle_identifier_number("");
            }
            else{
                profile.setVehicle_identifier_number(txtVehicleIdentifierNumber.getText());
            }
            
            // Placeholder for Device Identifier.
            if(txtDeviceIdentifier.getText().equals("Optional")){
                profile.setDevice_identifier("");
            }
            else{
                profile.setDevice_identifier(txtDeviceIdentifier.getText());
            }
            
            profile.setLinkedin(txtLinkedin.getText());
            profile.setIp_address(txtIPAddress.getText());
            profile.setPhoto(txtFilePath.getText());
            profile.setFingerprint(txtFilePathFingerprint.getText());

            
            JOptionPane.showMessageDialog(this, "Profile Saved Successfully!");
        }        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTelephoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNumberKeyReleased
        // TODO add your handling code here:
        String telephoneNumber = txtTelephoneNumber.getText();
//      Telephone number should be 10 digits long and only consist of numbers.
        if(telephoneNumber.matches("^[0-9]*$") && telephoneNumber.length() == 10)
        {
//            Change background colour and set the boolean variable as true.
            txtTelephoneNumber.setBackground(Color.green);
            this.isSubmit_telephoneNumber = true;
        }
        else{
//            Change background colour and set the boolean variable as false.
            txtTelephoneNumber.setBackground(Color.red);
            this.isSubmit_telephoneNumber = false;
        }
    }//GEN-LAST:event_txtTelephoneNumberKeyReleased

    private void txtFaxNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumberKeyReleased
        // TODO add your handling code here:
        String faxNumber = txtFaxNumber.getText();
//      Telephone number should be 9 digits long and only consist of numbers.
        if(faxNumber.matches("^[0-9]*$") && faxNumber.length() == 9)
        {
//            Change background colour and set the boolean variable as true.
            txtFaxNumber.setBackground(Color.green);
            this.isSubmit_FaxNumber = true;
        }
        else{
//            Change background colour and set the boolean variable as false.
            txtFaxNumber.setBackground(Color.red);
            this.isSubmit_FaxNumber = false;
        }
    }//GEN-LAST:event_txtFaxNumberKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        String ssnNumber = txtSSN.getText();
//      Telephone number should be 9 digits long and only consist of numbers.
        if(ssnNumber.matches("^[0-9]*$") && ssnNumber.length() == 9)
        {
//            Change background colour and set the boolean variable as true.
            txtSSN.setBackground(Color.green);
            isSubmit_SSN = true;
        }
        else{
//            Change background colour and set the boolean variable as false
            txtSSN.setBackground(Color.red);
            isSubmit_SSN = false;
        }
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtMedicalRecordNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberKeyReleased
        // TODO add your handling code here:
        String medicalRecordNumber = txtMedicalRecordNumber.getText();
//      Medical Record number should be 10 digits long and only consist of numbers.
        if(medicalRecordNumber.matches("^[a-zA-Z0-9]+$") && medicalRecordNumber.length() > 0)
        {
//            Change background colour and set the boolean variable as true.
            txtMedicalRecordNumber.setBackground(Color.green);
            this.isSubmit_MedicalRecordNumber = true;
        }
        else{
//            Change background colour and set the boolean variable as false
            txtMedicalRecordNumber.setBackground(Color.red);
            this.isSubmit_MedicalRecordNumber = false;
        }
    }//GEN-LAST:event_txtMedicalRecordNumberKeyReleased

    private void txtBankAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountNumberKeyReleased
        // TODO add your handling code here:
        String bankAccountNumber = txtBankAccountNumber.getText();
        /*
        Bank Account number should be greater than or equal to 10 digits long and 
        less than 18 digits long for simplicity and only consist of numbers.
        */
        if(bankAccountNumber.matches("^[0-9]*$") && bankAccountNumber.length() >= 10 && bankAccountNumber.length() <= 17)
        {
//            Change background colour and set the boolean variable as true.
            txtBankAccountNumber.setBackground(Color.green);
            this.isSubmit_BankAccountNumber = true;
        }
        else{
//            Change background colour and set the boolean variable as false
            txtBankAccountNumber.setBackground(Color.red);
            this.isSubmit_BankAccountNumber = false;
        }
    }//GEN-LAST:event_txtBankAccountNumberKeyReleased

    private void txtLicenseNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNumberKeyReleased
        // TODO add your handling code here:
        String LicenseNumber = txtLicenseNumber.getText();
//      License number should be 9 digits long and only consist of numbers.
        if(LicenseNumber.matches("^[0-9]*$") && LicenseNumber.length() == 9)
        {
//          Change background colour and set the boolean variable as true.
            txtLicenseNumber.setBackground(Color.green);
            this.isSubmit_LicenseNumber = true;
        }
        else{
//          Change background colour and set the boolean variable as false.
            txtLicenseNumber.setBackground(Color.red);
            this.isSubmit_LicenseNumber = false;
        }
    }//GEN-LAST:event_txtLicenseNumberKeyReleased

    private void txtIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyReleased
        // TODO add your handling code here:
        String IPAddress = txtIPAddress.getText();
//      REGEX for IPV4        
        String IPV4_REGEX =
                    "^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\." +
                    "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\." +
                    "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\." +
                    "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$";
        Pattern IPv4_PATTERN = Pattern.compile(IPV4_REGEX);
        Matcher matcher = IPv4_PATTERN.matcher(IPAddress);
        if (matcher.matches()) {
//          Change background colour and set the boolean variable as true.
            txtIPAddress.setBackground(Color.green);
            this.isSubmit_IPAddress = true;
        }
        else {
//          Change background colour and set the boolean variable as false
            txtIPAddress.setBackground(Color.red);
            this.isSubmit_IPAddress = false;
        }
        
        
        
    }//GEN-LAST:event_txtIPAddressKeyReleased

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        
//      FileChooser while helps us to choose a file.  
        JFileChooser chooser = new JFileChooser();
        int response = chooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
            FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
    //      Attaching Filter to JFileChooser object
            chooser.addChoosableFileFilter(imageFilter);
            chooser.setAcceptAllFileFilterUsed(false);

    //      Choose the selected file.
            File f = chooser.getSelectedFile();

    //      Get path of file and store it in filename variable.
            try {
                String filename = f.getAbsolutePath();
                txtFilePath.setText(filename);
                txtFilePath.setBackground(Color.green);

        //      Toolkit package to create an image.
                Image im = Toolkit.getDefaultToolkit().createImage(filename);
                im = im.getScaledInstance(txtViewPhoto.getWidth(), txtViewPhoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon ii = new ImageIcon(im);

        //      Display image on the JLabel.
                txtViewPhoto.setIcon(ii);
                this.isSubmit_Photo = true; 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please select a valid image.");
            }   
        }
        else{
            txtFilePath.setBackground(Color.white);
            this.isSubmit_Photo = false; 
            txtFilePath.setText("");
        }
        
        
    }//GEN-LAST:event_btnAttachActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String Name = txtName.getText();
        /*
            REGEX created for Name which consists of First Name and/or Middle Name and/or Last Name.
            First Name has to be minimum 2 characters and Last name has to be minimum 1 character.
        */
        String nameRegex = "^([a-zA-Z]{2,}\\s[a-zA-Z]{1,}'?-?[a-zA-Z]{2,}\\s?([a-zA-Z]{1,})?)";
        Pattern pattern = Pattern.compile(nameRegex);
        if(pattern.matcher(Name).matches())
        {
//          Change background colour and set the boolean variable as true.
            txtName.setBackground(Color.green);
            this.isSubmit_Name = true;
        }
        else{
//          Change background colour and set the boolean variable as false
            txtName.setBackground(Color.red);
            this.isSubmit_Name = false;
        }
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtVehicleIdentifierNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberFocusGained
        // TODO add your handling code here:
        
//      Placeholder for VehicleIdentifierName, If we click on Optional the text should go away.
        if(txtVehicleIdentifierNumber.getText().equals("Optional")){
            txtVehicleIdentifierNumber.setText("");
            txtVehicleIdentifierNumber.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_txtVehicleIdentifierNumberFocusGained

    private void txtDeviceIdentifierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierFocusGained
        // TODO add your handling code here:
        
//      Placeholder for txtDeviceIdentifier, If we click on Optional the text should go away.
        if(txtDeviceIdentifier.getText().equals("Optional")){
            txtDeviceIdentifier.setText("");
            txtDeviceIdentifier.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtDeviceIdentifierFocusGained

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        // TODO add your handling code here:

        String Address = txtAddress.getText();
        
//      Removing whitespace from address.
        String removed_whitespace_address = Address.replaceAll(" ", "");
        
//      REGEX for Address such that it should contain only alphanumeric characters and some other characters.
        String addressRegex = "^[a-zA-Z0-9\\s,'-]*$";
        Pattern pattern = Pattern.compile(addressRegex);
        txtAddress.setBackground(Color.red);
        if(pattern.matcher(Address).matches() && removed_whitespace_address.length() >= 4){
//          Change background colour and set the boolean variable as true.
            txtAddress.setBackground(Color.green);
            this.isSubmit_Address = true;
        }
        else{
//          Change background colour and set the boolean variable as false
            txtAddress.setBackground(Color.red);
            this.isSubmit_Address = false;
        }
        
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtVehicleIdentifierNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberFocusLost
        // TODO add your handling code here:
        
//      Placeholder for txtVehicleIdentifier, If there is no text then Optional should display.
        if(txtVehicleIdentifierNumber.getText().equals("")){
            txtVehicleIdentifierNumber.setText("Optional");
            txtVehicleIdentifierNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtVehicleIdentifierNumberFocusLost

    private void txtDeviceIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierFocusLost
        // TODO add your handling code here:
        
//      Placeholder for txtDeviceIdentifier, If there is no text then Optional should display.
        if(txtDeviceIdentifier.getText().equals("")){
            txtDeviceIdentifier.setText("Optional");
            txtDeviceIdentifier.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtDeviceIdentifierFocusLost

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // TODO add your handling code here:
        String Email = txtEmailAddress.getText();
        
//      REGEX to evaluate email address.
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        if(pattern.matcher(Email).matches()){
//          Change background colour and set the boolean variable as true.
            txtEmailAddress.setBackground(Color.green);
            this.isSubmit_EmailAddress = true;
        }
        else{
//          Change background colour and set the boolean variable as false
            txtEmailAddress.setBackground(Color.red);
            this.isSubmit_EmailAddress = false;        
        }
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtLinkedinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedinKeyReleased
        // TODO add your handling code here:
        String LinkedinURL = txtLinkedin.getText();
//      REGEX for LinkedIn URL.
        String linkedinRegex = "((https?:\\/\\/)?((www|\\w\\w)\\.)?linkedin\\.com\\/)((([\\w]{2,3})?)|([^\\/]+\\/(([\\w|\\d-&#?=])+\\/?){1,}))$";
        Pattern pattern = Pattern.compile(linkedinRegex);
        if(pattern.matcher(LinkedinURL).matches()){
//          Change background colour and set the boolean variable as true.
            txtLinkedin.setBackground(Color.green);
            this.isSubmit_LinkedinURL = true;
        } else{
//          Change background colour and set the boolean variable as false
            txtLinkedin.setBackground(Color.red);
            this.isSubmit_LinkedinURL = false;  
        }
    }//GEN-LAST:event_txtLinkedinKeyReleased

    private void btnAttachFingerprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachFingerprintActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
//      FileChooser while helps us to choose a file.  
        JFileChooser chooser = new JFileChooser();
        int response = chooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
            chooser.showOpenDialog(null);
            FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());

    //      Attaching Filter to JFileChooser object
            chooser.addChoosableFileFilter(imageFilter);
            chooser.setAcceptAllFileFilterUsed(false);

    //      Choose the selected file.
            File f = chooser.getSelectedFile();

    //      Get path of file and store it in filename variable.
            try {
                String filename_fingerprint = f.getAbsolutePath();
                txtFilePathFingerprint.setText(filename_fingerprint);

        //      Toolkit package to create an image.
                Image im = Toolkit.getDefaultToolkit().createImage(filename_fingerprint);
                im = im.getScaledInstance(txtViewFingerprint.getWidth(), txtViewFingerprint.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon ii = new ImageIcon(im);

        //      Display image on the JLabel.
                txtViewFingerprint.setIcon(ii);
                txtViewFingerprint.setBackground(Color.green);
                this.isSubmit_Fingerprint = true;
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Please select a valid fingerprint image.");            
            }
        }
        else{
            this.isSubmit_Photo = false; 
            txtViewFingerprint.setBackground(Color.white);
            txtFilePath.setText("");
        }

    }//GEN-LAST:event_btnAttachFingerprintActionPerformed

    private void txtVehicleIdentifierNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierNumberKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnAttachFingerprint;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lb1Title;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblFingerprint;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblVehicleIdentifierNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankAccountNumber;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtFilePathFingerprint;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtVehicleIdentifierNumber;
    private javax.swing.JLabel txtViewFingerprint;
    private javax.swing.JLabel txtViewPhoto;
    // End of variables declaration//GEN-END:variables
}
